In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
import optuna
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split,RandomizedSearchCV,GridSearchCV
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

/Users/kalp/PycharmProjects/Machine_learning/.venv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
df = pd.read_csv('Travel.csv')
df

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,204883,1,49.0,Self Enquiry,3,9.0,Small Business,Male,3,5.0,Deluxe,4.0,Unmarried,2.0,1,1,1,1.0,Manager,26576.0
4884,204884,1,28.0,Company Invited,1,31.0,Salaried,Male,4,5.0,Basic,3.0,Single,3.0,1,3,1,2.0,Executive,21212.0
4885,204885,1,52.0,Self Enquiry,3,17.0,Salaried,Female,4,4.0,Standard,4.0,Married,7.0,0,1,1,3.0,Senior Manager,31820.0
4886,204886,1,19.0,Self Enquiry,3,16.0,Small Business,Male,3,4.0,Basic,3.0,Single,3.0,0,5,0,2.0,Executive,20289.0
4887,204887,1,36.0,Self Enquiry,1,14.0,Salaried,Male,4,4.0,Basic,4.0,Unmarried,3.0,1,3,1,2.0,Executive,24041.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CustomerID                4888 non-null   int64
 1   ProdTaken                 4888 non-null   int64
 2   Age                       4662 non-null   float64
 3   TypeofContact             4863 non-null   object
 4   CityTier                  4888 non-null   int64
 5   DurationOfPitch           4637 non-null   float64
 6   Occupation                4888 non-null   object
 7   Gender                    4888 non-null   object
 8   NumberOfPersonVisiting    4888 non-null   int64
 9   NumberOfFollowups         4843 non-null   float64
 10  ProductPitched            4888 non-null   object
 11  PreferredPropertyStar     4862 non-null   float64
 12  MaritalStatus             4888 non-null   object
 13  NumberOfTrips             4748 non-null   float64
 14  Passport                  4888 non-null   int64
 15  PitchSatisfactionScore    4888 non-null   int64
 16  OwnCar                    4888 non-null   int64
 17  NumberOfChildrenVisiting  4822 non-null   float64
 18  Designation               4888 non-null   object
 19  MonthlyIncome             4655 non-null   float64
dtypes: float64(7), int64(7), object(6)
memory usage: 763.9+ KB

In [5]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

# DATA CLEANING

In [6]:
df.columns

Index(['CustomerID', 'ProdTaken', 'Age', 'TypeofContact', 'CityTier',
       'DurationOfPitch', 'Occupation', 'Gender', 'NumberOfPersonVisiting',
       'NumberOfFollowups', 'ProductPitched', 'PreferredPropertyStar',
       'MaritalStatus', 'NumberOfTrips', 'Passport', 'PitchSatisfactionScore',
       'OwnCar', 'NumberOfChildrenVisiting', 'Designation', 'MonthlyIncome'],
      dtype='object')

In [7]:
cols = ['TypeofContact', 'Occupation','Gender', 'ProductPitched','MaritalStatus','Designation']
for i in cols:
    print(df[i].value_counts())
    '\n'

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64
Occupation
Salaried          2368
Small Business    2084
Large Business     434
Free Lancer          2
Name: count, dtype: int64
Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64
ProductPitched
Basic           1842
Deluxe          1732
Standard         742
Super Deluxe     342
King             230
Name: count, dtype: int64
MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64
Designation
Executive         1842
Manager           1732
Senior Manager     742
AVP                342
VP                 230
Name: count, dtype: int64

In [8]:
df['Gender'] = df['Gender'].replace('Fe Male', 'Female')
df['MaritalStatus'] = df['MaritalStatus'].replace('Single','Unmarried')

In [9]:
df['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [10]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Unmarried    1598
Divorced      950
Name: count, dtype: int64

In [11]:
features_with_nan = [features for features in df.columns if df[features].isnull().sum()>=1 ]
for i in features_with_nan:
    print(i,np.round(df[i].isnull().mean()*100,5),'%')

Age 4.62357 %
TypeofContact 0.51146 %
DurationOfPitch 5.13502 %
NumberOfFollowups 0.92062 %
PreferredPropertyStar 0.53191 %
NumberOfTrips 2.86416 %
NumberOfChildrenVisiting 1.35025 %
MonthlyIncome 4.76678 %

In [12]:
df[features_with_nan].select_dtypes(exclude='object').describe()

,Age,DurationOfPitch,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,NumberOfChildrenVisiting,MonthlyIncome
count,4662.000000,4637.000000,4843.000000,4862.000000,4748.000000,4822.000000,4655.000000
mean,37.622265,15.490835,3.708445,3.581037,3.236521,1.187267,23619.853491
std,9.316387,8.519643,1.002509,0.798009,1.849019,0.857861,5380.698361
min,18.000000,5.000000,1.000000,3.000000,1.000000,0.000000,1000.000000
25%,31.000000,9.000000,3.000000,3.000000,2.000000,1.000000,20346.000000
50%,36.000000,13.000000,4.000000,3.000000,3.000000,1.000000,22347.000000
75%,44.000000,20.000000,4.000000,4.000000,4.000000,2.000000,25571.000000
max,61.000000,127.000000,6.000000,5.000000,22.000000,3.000000,98678.000000

In [13]:
df['Age'].fillna(df['Age'].median(),inplace=True)
df['TypeofContact'].fillna(df['TypeofContact'].mode()[0],inplace=True)
df['DurationOfPitch'].fillna(df['DurationOfPitch'].median(),inplace=True)
df['NumberOfFollowups'].fillna(df['NumberOfFollowups'].median(),inplace=True)
df['PreferredPropertyStar'].fillna(df['PreferredPropertyStar'].mode()[0],inplace=True)
df['NumberOfTrips'].fillna(df['NumberOfTrips'].median(),inplace=True)
df['NumberOfChildrenVisiting'].fillna(df['NumberOfChildrenVisiting'].mode()[0],inplace=True)
df['MonthlyIncome'].fillna(df['MonthlyIncome'].median(),inplace=True)

In [14]:
df.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [15]:
df.drop(columns=['CustomerID'],axis=1,inplace=True)

In [16]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [17]:
df['TotalVisiting'] = df['NumberOfPersonVisiting'] + df['NumberOfChildrenVisiting']
df.drop(columns=['NumberOfChildrenVisiting','NumberOfPersonVisiting'],axis=1,inplace=True)

In [18]:
num_features = [feature for feature in df.columns if df[feature].dtypes!='object']
print(num_features)

['ProdTaken', 'Age', 'CityTier', 'DurationOfPitch', 'NumberOfFollowups', 'PreferredPropertyStar', 'NumberOfTrips', 'Passport', 'PitchSatisfactionScore', 'OwnCar', 'MonthlyIncome', 'TotalVisiting']

In [19]:
cat_features = [feature for feature in df.columns if df[feature].dtypes=='object']
print(cat_features)

['TypeofContact', 'Occupation', 'Gender', 'ProductPitched', 'MaritalStatus', 'Designation']

In [20]:
discrete_features = [feature for feature in num_features if len(df[feature].unique())<=25]
print(discrete_features)

['ProdTaken', 'CityTier', 'NumberOfFollowups', 'PreferredPropertyStar', 'NumberOfTrips', 'Passport', 'PitchSatisfactionScore', 'OwnCar', 'TotalVisiting']

In [21]:
cont_features = [feature for feature in num_features if feature not in discrete_features]
print(cont_features)

['Age', 'DurationOfPitch', 'MonthlyIncome']

In [22]:
X = df.drop(columns=['ProdTaken'],axis=1)
y = df['ProdTaken']

In [23]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [24]:
y.value_counts()

ProdTaken
0    3968
1     920
Name: count, dtype: int64

## COLUMN TRANSFORMER

This estimator allows different columns or column subsets of the input to be transformed separately and the features generated by each transformer will be concatenated to form a single feature space. This is useful for heterogeneous or columnar data, to combine several feature extraction mechanisms or transformations into a single transformer.

In [25]:
cate_features = X.select_dtypes(include='object').columns
nume_features = X.select_dtypes(exclude='object').columns

ohe = OneHotEncoder(drop='first')
numeric_transformer = StandardScaler()

preprocessor = ColumnTransformer(
    [
        ('ohe', ohe, cate_features),
        ('numeric', numeric_transformer, nume_features)
    ]
)

In [26]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)
X_train

array([[ 1.        ,  0.        ,  0.        , ...,  0.78296635,
        -0.38224537, -0.77415132],
       [ 1.        ,  0.        ,  1.        , ...,  0.78296635,
        -0.4597992 ,  0.64361526],
       [ 1.        ,  1.        ,  0.        , ...,  0.78296635,
        -0.24519557, -0.06526803],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.78296635,
        -0.36057591,  0.64361526],
       [ 1.        ,  0.        ,  0.        , ...,  0.78296635,
        -0.25279888,  0.64361526],
       [ 0.        ,  0.        ,  1.        , ..., -1.2771941 ,
        -1.08251091, -1.48303461]])

In [27]:
models = {
    'Random Forest':RandomForestClassifier(),
    'AdaBoost':AdaBoostClassifier(),
    'Decision Tree':DecisionTreeClassifier(),
    'Logistic Regression':LogisticRegression(),
    'Xgboost':XGBClassifier()
}
for i in range(len(list(models))):
    model = models[list(models)[i]]
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    print(f'{list(models)[i]} Accuracy: {accuracy_score(y_test,y_pred)}')
    print(f'{list(models)[i]} Confusion Matrix: \n{confusion_matrix(y_test,y_pred)}')
    print(f'{list(models)[i]} Classification Report: \n{classification_report(y_test,y_pred)}')
    print('\n')

Random Forest Accuracy: 0.9314928425357873
Random Forest Confusion Matrix:
[[784   3]
 [ 64 127]]
Random Forest Classification Report:
              precision    recall  f1-score   support

           0       0.92      1.00      0.96       787
           1       0.98      0.66      0.79       191

    accuracy                           0.93       978
   macro avg       0.95      0.83      0.88       978
weighted avg       0.93      0.93      0.93       978



AdaBoost Accuracy: 0.8353783231083844
AdaBoost Confusion Matrix:
[[772  15]
 [146  45]]
AdaBoost Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.98      0.91       787
           1       0.75      0.24      0.36       191

    accuracy                           0.84       978
   macro avg       0.80      0.61      0.63       978
weighted avg       0.82      0.84      0.80       978



Decision Tree Accuracy: 0.9192229038854806
Decision Tree Confusion Matrix:
[[756  31]
 [ 48 143]]
Decision Tree Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.96      0.95       787
           1       0.82      0.75      0.78       191

    accuracy                           0.92       978
   macro avg       0.88      0.85      0.87       978
weighted avg       0.92      0.92      0.92       978



Logistic Regression Accuracy: 0.83640081799591
Logistic Regression Confusion Matrix:
[[762  25]
 [135  56]]
Logistic Regression Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.97      0.90       787
           1       0.69      0.29      0.41       191

    accuracy                           0.84       978
   macro avg       0.77      0.63      0.66       978
weighted avg       0.82      0.84      0.81       978



Xgboost Accuracy: 0.9427402862985685
Xgboost Confusion Matrix:
[[780   7]
 [ 49 142]]
Xgboost Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.99      0.97       787
           1       0.95      0.74      0.84       191

    accuracy                           0.94       978
   macro avg       0.95      0.87      0.90       978
weighted avg       0.94      0.94      0.94       978

# HYPER-PARAMETER TUNING

In [28]:
rf_params = {
    'max_depth': [5,8,15,None,10],
    'max_features': ['auto','sqrt','log2',5,6,7],
    'n_estimators': [100,500,1000],
    'min_samples_split': [2,5,10,15,20]
}
ada_params = {
    'n_estimators': [10,50,100,250,500],
    'learning_rate': [0.001,0.01,0.1,1,10],
}

In [29]:
cv_models = [
    ('RF',RandomForestClassifier(),rf_params),
    ('AdaBoost',AdaBoostClassifier(),ada_params)
]

In [30]:
model_params = {}

for name,model,params in cv_models:
    random = RandomizedSearchCV(estimator=model,param_distributions=params,n_iter=10,cv=3,verbose=2,n_jobs=-1)
    random.fit(X_train,y_train)
    model_params[name] = random.best_params_
    print(f'Best Parameters for {name}: {model_params[name]}')
    grid = GridSearchCV(estimator=model,param_grid=params,cv=3,verbose=2,n_jobs=-1)
    grid.fit(X_train,y_train)
    print(f'Best Parameters for {name}: {grid.best_params_}')
    print('\n')

Fitting 3 folds for each of 10 candidates, totalling 30 fits
[CV] END max_depth=None, max_features=6, min_samples_split=20, n_estimators=100; total time=   0.2s
[CV] END max_depth=None, max_features=6, min_samples_split=20, n_estimators=100; total time=   0.2s
[CV] END max_depth=None, max_features=6, min_samples_split=20, n_estimators=100; total time=   0.2s
[CV] END max_depth=8, max_features=6, min_samples_split=10, n_estimators=100; total time=   0.2s
[CV] END max_depth=8, max_features=6, min_samples_split=10, n_estimators=100; total time=   0.2s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=2, n_estimators=500; total time=   0.8s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=2, n_estimators=500; total time=   0.8s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=2, n_estimators=500; total time=   0.8s
[CV] END max_depth=8, max_features=6, min_samples_split=10, n_estimators=100; total time=   0.2s
[CV] END max_depth=8, max_features=6, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END max_depth=8, max_features=6, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END max_depth=8, max_features=6, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END max_depth=None, max_features=7, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END max_depth=None, max_features=7, min_samples_split=2, n_estimators=100; total time=   0.3s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=500; total time=   0.8s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=500; total time=   0.8s
[CV] END max_depth=None, max_features=7, min_samples_split=2, n_estimators=100; total time=   0.3s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=500; total time=   0.8s
[CV] END max_depth=8, max_features=6, min_samples_split=15, n_estimators=1000; total time=   1.9s
[CV] END max_depth=8, max_features=6, min_samples_split=15, n_estimators=1000; total time=   2.0s
[CV] END max_depth=8, max_features=6, min_samples_split=15, n_estimators=1000; total time=   2.0s
[CV] END max_depth=None, max_features=sqrt, min_samples_split=5, n_estimators=1000; total time=   2.1s
[CV] END max_depth=None, max_features=sqrt, min_samples_split=5, n_estimators=1000; total time=   2.0s
[CV] END max_depth=None, max_features=sqrt, min_samples_split=5, n_estimators=1000; total time=   2.0s
Best Parameters for RF: {'n_estimators': 100, 'min_samples_split': 2, 'max_features': 7, 'max_depth': None}
Fitting 3 folds for each of 450 candidates, totalling 1350 fits
[CV] END max_depth=5, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=5, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=5, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=5, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=5, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=5, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=5, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=5, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=5, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=5, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=10, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=10, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=10, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=10, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=10, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=10, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=10, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=10, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=15, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=15, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=2, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=2, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=15, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=5, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=5, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=10, n_estimators=500; total time=   0.8s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=15, n_estimators=500; total time=   0.6s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=10, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=2, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=15, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=5, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=2, n_estimators=1000; total time=   1.4s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=5, n_estimators=1000; total time=   1.4s
[CV] END max_depth=5, max_features=log2, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=15, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=10, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=20, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=2, n_estimators=1000; total time=   1.4s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=15, n_estimators=1000; total time=   1.3s
[CV] END max_depth=5, max_features=log2, min_samples_split=2, n_estimators=500; total time=   0.6s
[CV] END max_depth=5, max_features=log2, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=20, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=10, n_estimators=1000; total time=   1.5s
[CV] END max_depth=5, max_features=log2, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=20, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=20, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=20, n_estimators=1000; total time=   1.4s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=20, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=2, n_estimators=1000; total time=   1.3s
[CV] END max_depth=5, max_features=log2, min_samples_split=2, n_estimators=500; total time=   0.6s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=5, n_estimators=1000; total time=   1.4s
[CV] END max_depth=5, max_features=log2, min_samples_split=10, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=log2, min_samples_split=2, n_estimators=1000; total time=   1.3s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=15, n_estimators=1000; total time=   1.4s
[CV] END max_depth=5, max_features=log2, min_samples_split=10, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=log2, min_samples_split=5, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=log2, min_samples_split=10, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=log2, min_samples_split=5, n_estimators=500; total time=   0.6s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=20, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=log2, min_samples_split=2, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=log2, min_samples_split=5, n_estimators=500; total time=   0.8s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=10, n_estimators=1000; total time=   1.5s
[CV] END max_depth=5, max_features=log2, min_samples_split=10, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=log2, min_samples_split=10, n_estimators=500; total time=   0.8s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=20, n_estimators=1000; total time=   1.6s
[CV] END max_depth=5, max_features=log2, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=5, n_estimators=1000; total time=   1.7s
[CV] END max_depth=5, max_features=log2, min_samples_split=2, n_estimators=1000; total time=   1.6s
[CV] END max_depth=5, max_features=log2, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=10, n_estimators=100; total time=   0.2s
[CV] END max_depth=5, max_features=log2, min_samples_split=15, n_estimators=500; total time=   0.8s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=15, n_estimators=1000; total time=   1.7s
[CV] END max_depth=5, max_features=log2, min_samples_split=5, n_estimators=1000; total time=   1.6s
[CV] END max_depth=5, max_features=log2, min_samples_split=20, n_estimators=100; total time=   0.2s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=20, n_estimators=1000; total time=   1.5s
[CV] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=log2, min_samples_split=10, n_estimators=500; total time=   0.8s
[CV] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=log2, min_samples_split=10, n_estimators=1000; total time=   1.6s
[CV] END max_depth=5, max_features=log2, min_samples_split=15, n_estimators=500; total time=   0.8s
[CV] END max_depth=5, max_features=sqrt, min_samples_split=10, n_estimators=1000; total time=   1.7s
[CV] END max_depth=5, max_features=log2, min_samples_split=15, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=log2, min_samples_split=20, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=log2, min_samples_split=15, n_estimators=100; total time=   0.2s
[CV] END max_depth=5, max_features=log2, min_samples_split=15, n_estimators=100; total time=   0.2s
[CV] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=500; total time=   0.9s
[CV] END max_depth=5, max_features=log2, min_samples_split=2, n_estimators=1000; total time=   1.5s
[CV] END max_depth=5, max_features=5, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END max_depth=5, max_features=log2, min_samples_split=15, n_estimators=500; total time=   0.8s
[CV] END max_depth=5, max_features=log2, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END max_depth=5, max_features=log2, min_samples_split=15, n_estimators=1000; total time=   1.6s
[CV] END max_depth=5, max_features=5, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END max_depth=5, max_features=log2, min_samples_split=20, n_estimators=1000; total time=   1.5s
[CV] END max_depth=5, max_features=log2, min_samples_split=5, n_estimators=1000; total time=   1.6s
[CV] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=500; total time=   0.9s
[CV] END max_depth=5, max_features=log2, min_samples_split=20, n_estimators=500; total time=   0.8s
[CV] END max_depth=5, max_features=5, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END max_depth=5, max_features=log2, min_samples_split=10, n_estimators=1000; total time=   1.7s
[CV] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=500; total time=   0.8s
[CV] END max_depth=5, max_features=5, min_samples_split=5, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=log2, min_samples_split=20, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=5, min_samples_split=5, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=log2, min_samples_split=15, n_estimators=1000; total time=   1.4s
[CV] END max_depth=5, max_features=log2, min_samples_split=15, n_estimators=1000; total time=   1.4s
[CV] END max_depth=5, max_features=5, min_samples_split=5, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=log2, min_samples_split=20, n_estimators=1000; total time=   1.4s
[CV] END max_depth=5, max_features=log2, min_samples_split=5, n_estimators=1000; total time=   1.4s
[CV] END max_depth=5, max_features=log2, min_samples_split=20, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=5, min_samples_split=15, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=5, min_samples_split=10, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=1000; total time=   1.5s
[CV] END max_depth=5, max_features=log2, min_samples_split=20, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=log2, min_samples_split=10, n_estimators=1000; total time=   1.3s
[CV] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=100; total time=   0.2s
[CV] END max_depth=5, max_features=5, min_samples_split=5, n_estimators=1000; total time=   1.5s
[CV] END max_depth=5, max_features=5, min_samples_split=10, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=5, min_samples_split=10, n_estimators=1000; total time=   1.4s
[CV] END max_depth=5, max_features=5, min_samples_split=15, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=5, min_samples_split=10, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=5, min_samples_split=10, n_estimators=100; total time=   0.2s
[CV] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=500; total time=   0.6s
[CV] END max_depth=5, max_features=5, min_samples_split=10, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=6, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=6, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=log2, min_samples_split=20, n_estimators=1000; total time=   1.3s
[CV] END max_depth=5, max_features=5, min_samples_split=5, n_estimators=1000; total time=   1.5s
[CV] END max_depth=5, max_features=6, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END max_depth=5, max_features=5, min_samples_split=15, n_estimators=1000; total time=   1.4s
[CV] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=100; total time=   0.2s
[CV] END max_depth=5, max_features=5, min_samples_split=15, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=5, min_samples_split=10, n_estimators=500; total time=   0.7s
[CV] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=1000; total time=   1.5s

KeyboardInterrupt:

In [35]:
grid.best_params_

{'learning_rate': 1, 'n_estimators': 100}

In [36]:
random.best_params_

{'n_estimators': 500, 'learning_rate': 1}

In [37]:
y_pred = random.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.8394683026584867
              precision    recall  f1-score   support

           0       0.85      0.97      0.91       787
           1       0.71      0.30      0.42       191

    accuracy                           0.84       978
   macro avg       0.78      0.64      0.67       978
weighted avg       0.82      0.84      0.81       978

[[763  24]
 [133  58]]

In [38]:
y_pred = grid.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.8384458077709611
              precision    recall  f1-score   support

           0       0.84      0.98      0.91       787
           1       0.79      0.24      0.36       191

    accuracy                           0.84       978
   macro avg       0.82      0.61      0.64       978
weighted avg       0.83      0.84      0.80       978

[[775  12]
 [146  45]]

In [39]:
def objective(trial):
    params = {
        'learning_rate': trial.suggest_float('learning_rate',0,1),
        'n_estimators': trial.suggest_int('n_estimators',low=5,high=1000,log=True)
    }
    model = AdaBoostClassifier(**params)
    score = accuracy_score(y_test,y_pred)
    return score
study = optuna.create_study(direction='maximize')
study.optimize(objective,n_trials=1000)
print(study.best_params)

[I 2025-11-01 14:50:37,672] A new study created in memory with name: no-name-48ecbd42-5871-405e-9add-98507511c394
[I 2025-11-01 14:50:37,680] Trial 0 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.9766218470915263, 'n_estimators': 54}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,682] Trial 1 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.40323593006052727, 'n_estimators': 36}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,683] Trial 2 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.5575767982969759, 'n_estimators': 6}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,684] Trial 3 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.36761747898717256, 'n_estimators': 403}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,685] Trial 4 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.8997891013184535, 'n_estimators': 11}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,686] Trial 5 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.24893282701265818, 'n_estimators': 206}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,687] Trial 6 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.020856405386177723, 'n_estimators': 312}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,688] Trial 7 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.8456386856115568, 'n_estimators': 29}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,689] Trial 8 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.44361662152672154, 'n_estimators': 578}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,690] Trial 9 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.0022711816228929704, 'n_estimators': 89}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,695] Trial 10 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.7096592153440637, 'n_estimators': 102}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,697] Trial 11 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.6509869544399602, 'n_estimators': 26}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,700] Trial 12 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.22162738872472787, 'n_estimators': 35}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,702] Trial 13 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.3112940582499703, 'n_estimators': 53}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,704] Trial 14 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.9914574245155574, 'n_estimators': 12}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,706] Trial 15 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.5667166217184181, 'n_estimators': 134}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,708] Trial 16 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.7528698373885434, 'n_estimators': 17}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,710] Trial 17 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.13509162403792002, 'n_estimators': 54}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,712] Trial 18 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.44179796131372767, 'n_estimators': 876}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,714] Trial 19 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.6054531322649626, 'n_estimators': 5}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,716] Trial 20 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.7669483527458243, 'n_estimators': 199}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,718] Trial 21 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.48678642195323407, 'n_estimators': 6}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,719] Trial 22 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.5493915107459685, 'n_estimators': 8}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,722] Trial 23 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.3755536780952231, 'n_estimators': 20}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,723] Trial 24 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.943945860418681, 'n_estimators': 38}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,725] Trial 25 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.8222620773654831, 'n_estimators': 14}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,726] Trial 26 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.6496142952791166, 'n_estimators': 71}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,729] Trial 27 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.1370418914508046, 'n_estimators': 7}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,730] Trial 28 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.3915093510350235, 'n_estimators': 46}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,732] Trial 29 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.28617615267731056, 'n_estimators': 22}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,734] Trial 30 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.5330134392921668, 'n_estimators': 163}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,736] Trial 31 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.36948697741566533, 'n_estimators': 329}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,738] Trial 32 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.20630930566821334, 'n_estimators': 9}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,740] Trial 33 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.3083911890415514, 'n_estimators': 335}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,741] Trial 34 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.4749714036172365, 'n_estimators': 111}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,743] Trial 35 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.13109653286008272, 'n_estimators': 78}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,745] Trial 36 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.8822332272444223, 'n_estimators': 515}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,747] Trial 37 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.40773650783613546, 'n_estimators': 237}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,749] Trial 38 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.3456667748141382, 'n_estimators': 29}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,751] Trial 39 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.6836171650382614, 'n_estimators': 962}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,753] Trial 40 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.07815158042460835, 'n_estimators': 61}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,754] Trial 41 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.9006871035503673, 'n_estimators': 11}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,756] Trial 42 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.9421376792590218, 'n_estimators': 5}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,758] Trial 43 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.8188253642790763, 'n_estimators': 16}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,760] Trial 44 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.2550772766717899, 'n_estimators': 40}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,762] Trial 45 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.9593632520485063, 'n_estimators': 25}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,764] Trial 46 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.5955401333402912, 'n_estimators': 97}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,766] Trial 47 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.9882519738744495, 'n_estimators': 10}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,767] Trial 48 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.7428999241848636, 'n_estimators': 13}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,769] Trial 49 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.881279770593281, 'n_estimators': 129}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,771] Trial 50 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.44249891360356414, 'n_estimators': 6}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,774] Trial 51 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.2548747683508437, 'n_estimators': 459}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,776] Trial 52 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.33325601594040066, 'n_estimators': 714}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,778] Trial 53 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.19180750459012408, 'n_estimators': 396}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,781] Trial 54 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.521169119150497, 'n_estimators': 252}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,784] Trial 55 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.7985522197377635, 'n_estimators': 33}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,786] Trial 56 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.43496490749882, 'n_estimators': 7}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,788] Trial 57 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.27857165043229043, 'n_estimators': 642}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,789] Trial 58 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.489313342385598, 'n_estimators': 161}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,792] Trial 59 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.9156761911648834, 'n_estimators': 50}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,794] Trial 60 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.84534013251209, 'n_estimators': 18}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,796] Trial 61 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.018785243617000458, 'n_estimators': 310}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,798] Trial 62 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.16084438912905064, 'n_estimators': 204}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,800] Trial 63 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.05042865208531783, 'n_estimators': 271}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,802] Trial 64 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.41056937365675583, 'n_estimators': 432}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,804] Trial 65 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.0827662015387807, 'n_estimators': 170}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,806] Trial 66 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.3486012698270823, 'n_estimators': 779}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,808] Trial 67 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.5674264883827064, 'n_estimators': 79}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,809] Trial 68 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.6662573245346405, 'n_estimators': 59}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,811] Trial 69 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.3137671432305429, 'n_estimators': 116}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,813] Trial 70 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.2319907180286707, 'n_estimators': 8}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,815] Trial 71 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.98760058468569, 'n_estimators': 40}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,817] Trial 72 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.8587254918720599, 'n_estimators': 29}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,819] Trial 73 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.9288136975720331, 'n_estimators': 15}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,821] Trial 74 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.7166167246084612, 'n_estimators': 583}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,824] Trial 75 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.7786667668558933, 'n_estimators': 24}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,825] Trial 76 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.38341498053676903, 'n_estimators': 44}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,828] Trial 77 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.6368002288028823, 'n_estimators': 33}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,829] Trial 78 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.4717356513135074, 'n_estimators': 70}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,832] Trial 79 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.9575265138651985, 'n_estimators': 20}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,834] Trial 80 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.8892499438206433, 'n_estimators': 11}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,836] Trial 81 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.4473829494451173, 'n_estimators': 360}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,838] Trial 82 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.5065342583383883, 'n_estimators': 465}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,840] Trial 83 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.5520195168058415, 'n_estimators': 6}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,842] Trial 84 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.4122868287419618, 'n_estimators': 87}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,844] Trial 85 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.3674973058831241, 'n_estimators': 512}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,846] Trial 86 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.1737950871348836, 'n_estimators': 305}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,848] Trial 87 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.308529994451865, 'n_estimators': 385}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,850] Trial 88 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.9994245485923606, 'n_estimators': 601}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,852] Trial 89 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.11765287467611113, 'n_estimators': 212}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,854] Trial 90 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.8637576908786568, 'n_estimators': 50}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,856] Trial 91 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.010870453900630772, 'n_estimators': 5}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,858] Trial 92 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.5949420398316566, 'n_estimators': 141}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,860] Trial 93 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.04270853326643577, 'n_estimators': 265}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,862] Trial 94 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.10532190602576078, 'n_estimators': 9}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,864] Trial 95 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.4613706033607641, 'n_estimators': 28}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,867] Trial 96 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.04143673509107568, 'n_estimators': 63}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,869] Trial 97 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.07678234009179577, 'n_estimators': 879}. Best is trial 0 with value: 0.8384458077709611.
[I 2025-11-01 14:50:37,871] Trial 98 finished with value: 0.8384458077709611 and parameters: {'learning_rate': 0.9122969855391483, 'n_estimators': 35}. Best is trial 0 with value: 0.8384458077709611.

{'learning_rate': 0.9766218470915263, 'n_estimators': 54}

In [40]:
best_params = study.best_params
boost = AdaBoostClassifier(**best_params)
boost.fit(X_train,y_train)
y_pred = boost.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.8404907975460123

## HYPER-PARAMETER TUNING XGBOOST USING OPTUNA

In [48]:
def objective(trial):
    booster = trial.suggest_categorical('booster',['gbtree','dart','gblinear'])
    params = {
        "booster":booster,
        'n_estimators':trial.suggest_int('n_estimators',low=5,high=1000,log=True),
        'learning_rate':trial.suggest_float('learning_rate',low=0.1,high=1,log=True),
    }
    if booster in ['gbtree','dart']:
        params.update({
            'max_depth':trial.suggest_int('max_depth',low=1,high=15,step=1),
            'min_child_weight':trial.suggest_int('min_child_weight',low=1,high=10,step=1),
            'gamma':trial.suggest_float('gamma',low=0.1,high=1,log=True),
            'reg_alpha':trial.suggest_float('reg_alpha',low=0.1,high=1,log=True),
            'reg_lambda':trial.suggest_float('reg_lambda',low=0.1,high=1,log=True),
        })
    model = XGBClassifier(**params)
    accuracy = accuracy_score(y_test,y_pred)
    return accuracy

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=1000)

[I 2025-11-01 14:58:02,171] A new study created in memory with name: no-name-837d27e4-ec03-4db8-86ff-4698b4cf1caa
[I 2025-11-01 14:58:02,175] Trial 0 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 632, 'learning_rate': 0.29019543782476226}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,176] Trial 1 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 231, 'learning_rate': 0.3024451621079473}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,178] Trial 2 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 157, 'learning_rate': 0.7396935686641946, 'max_depth': 8, 'min_child_weight': 4, 'gamma': 0.6448756239622311, 'reg_alpha': 0.11531605929219545, 'reg_lambda': 0.13092218419377782}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,179] Trial 3 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 9, 'learning_rate': 0.7832216637933078}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,181] Trial 4 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 743, 'learning_rate': 0.4744357741729917, 'max_depth': 4, 'min_child_weight': 10, 'gamma': 0.7864572430330539, 'reg_alpha': 0.17619779813640515, 'reg_lambda': 0.17092090484045697}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,182] Trial 5 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 923, 'learning_rate': 0.4359690400256699, 'max_depth': 13, 'min_child_weight': 2, 'gamma': 0.26222081365206124, 'reg_alpha': 0.2064345261645537, 'reg_lambda': 0.857732812075956}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,184] Trial 6 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 14, 'learning_rate': 0.5938835717535574, 'max_depth': 7, 'min_child_weight': 8, 'gamma': 0.8023549369856764, 'reg_alpha': 0.7780481750417378, 'reg_lambda': 0.10728559933879547}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,185] Trial 7 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 67, 'learning_rate': 0.31406911598511156}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,186] Trial 8 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 6, 'learning_rate': 0.7510299239515525, 'max_depth': 10, 'min_child_weight': 1, 'gamma': 0.4420949835701655, 'reg_alpha': 0.8519938775294107, 'reg_lambda': 0.11120586976077879}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,187] Trial 9 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 27, 'learning_rate': 0.21320278133731008}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,194] Trial 10 finished with value: 0.9212678936605317 and parameters: {'booster': 'dart', 'n_estimators': 315, 'learning_rate': 0.10747909996349453, 'max_depth': 2, 'min_child_weight': 5, 'gamma': 0.11270415613478799, 'reg_alpha': 0.42374700589973185, 'reg_lambda': 0.6373954120252625}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,196] Trial 11 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 281, 'learning_rate': 0.24051253222820412}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,199] Trial 12 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 120, 'learning_rate': 0.14170824845867563}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,205] Trial 13 finished with value: 0.9212678936605317 and parameters: {'booster': 'dart', 'n_estimators': 416, 'learning_rate': 0.2999696957492246, 'max_depth': 15, 'min_child_weight': 8, 'gamma': 0.10392720348192196, 'reg_alpha': 0.42849338465285125, 'reg_lambda': 0.3515919654468697}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,207] Trial 14 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 70, 'learning_rate': 0.1945746252277921}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,209] Trial 15 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 523, 'learning_rate': 0.38748709065676645}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,214] Trial 16 finished with value: 0.9212678936605317 and parameters: {'booster': 'dart', 'n_estimators': 188, 'learning_rate': 0.17252870395516998, 'max_depth': 1, 'min_child_weight': 7, 'gamma': 0.22198963737837502, 'reg_alpha': 0.27089139761004283, 'reg_lambda': 0.2592867909395813}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,216] Trial 17 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 72, 'learning_rate': 0.2665206805444994}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,218] Trial 18 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 539, 'learning_rate': 0.3616313549589521}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,219] Trial 19 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 107, 'learning_rate': 0.530350410017252}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,224] Trial 20 finished with value: 0.9212678936605317 and parameters: {'booster': 'dart', 'n_estimators': 33, 'learning_rate': 0.1476304994076816, 'max_depth': 11, 'min_child_weight': 3, 'gamma': 0.18263822839011945, 'reg_alpha': 0.10961457569809797, 'reg_lambda': 0.44531094544670125}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,229] Trial 21 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 195, 'learning_rate': 0.9399905277852799, 'max_depth': 7, 'min_child_weight': 4, 'gamma': 0.4541627240456259, 'reg_alpha': 0.11223509074276516, 'reg_lambda': 0.19885940533695917}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,233] Trial 22 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 190, 'learning_rate': 0.36570839062299476, 'max_depth': 5, 'min_child_weight': 6, 'gamma': 0.4777128519150655, 'reg_alpha': 0.18155729504269508, 'reg_lambda': 0.16098849520040254}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,238] Trial 23 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 343, 'learning_rate': 0.5969472554007648, 'max_depth': 10, 'min_child_weight': 4, 'gamma': 0.9100939348120556, 'reg_alpha': 0.10317275598559933, 'reg_lambda': 0.2543116391947755}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,240] Trial 24 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 671, 'learning_rate': 0.2621149670898396}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,245] Trial 25 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 118, 'learning_rate': 0.31680072124428477, 'max_depth': 4, 'min_child_weight': 10, 'gamma': 0.5775700772444227, 'reg_alpha': 0.513429358344637, 'reg_lambda': 0.47056698821416765}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,247] Trial 26 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 220, 'learning_rate': 0.43087210229509115}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,249] Trial 27 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 448, 'learning_rate': 0.23879902885667414}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,254] Trial 28 finished with value: 0.9212678936605317 and parameters: {'booster': 'dart', 'n_estimators': 921, 'learning_rate': 0.7134407021344091, 'max_depth': 8, 'min_child_weight': 1, 'gamma': 0.2933949947826683, 'reg_alpha': 0.26341802241381307, 'reg_lambda': 0.1405307717353876}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,259] Trial 29 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 43, 'learning_rate': 0.9761486920634203, 'max_depth': 15, 'min_child_weight': 3, 'gamma': 0.619814060050479, 'reg_alpha': 0.14584753634014835, 'reg_lambda': 0.2260215082263473}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,261] Trial 30 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 140, 'learning_rate': 0.196741700286255}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,263] Trial 31 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 5, 'learning_rate': 0.7994204512754923}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,265] Trial 32 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 9, 'learning_rate': 0.49174730404075134}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,270] Trial 33 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 24, 'learning_rate': 0.6083089762539104, 'max_depth': 12, 'min_child_weight': 5, 'gamma': 0.15847995522624778, 'reg_alpha': 0.6430695343386538, 'reg_lambda': 0.32799895573482835}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,273] Trial 34 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 14, 'learning_rate': 0.6733159425644537}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,277] Trial 35 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 789, 'learning_rate': 0.8205926733958073, 'max_depth': 6, 'min_child_weight': 6, 'gamma': 0.3595522033350153, 'reg_alpha': 0.3455130631761589, 'reg_lambda': 0.13312442214001982}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,280] Trial 36 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 49, 'learning_rate': 0.4310169940180775}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,284] Trial 37 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 269, 'learning_rate': 0.31732562789513397, 'max_depth': 9, 'min_child_weight': 8, 'gamma': 0.6373326929761637, 'reg_alpha': 0.15360168979047467, 'reg_lambda': 0.9541773166892761}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,286] Trial 38 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 9, 'learning_rate': 0.5039867871897069}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,289] Trial 39 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 17, 'learning_rate': 0.645398554854811}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,294] Trial 40 finished with value: 0.9212678936605317 and parameters: {'booster': 'dart', 'n_estimators': 86, 'learning_rate': 0.8664047822902932, 'max_depth': 3, 'min_child_weight': 3, 'gamma': 0.34299566956690863, 'reg_alpha': 0.24675175926639756, 'reg_lambda': 0.4720917979463961}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,299] Trial 41 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 648, 'learning_rate': 0.5390478309687408, 'max_depth': 4, 'min_child_weight': 9, 'gamma': 0.7592143340636864, 'reg_alpha': 0.14530220127443955, 'reg_lambda': 0.18015659030061493}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,303] Trial 42 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 370, 'learning_rate': 0.39811198678306625, 'max_depth': 6, 'min_child_weight': 10, 'gamma': 0.924358125157118, 'reg_alpha': 0.20116497196399402, 'reg_lambda': 0.13371876200384678}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,308] Trial 43 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 930, 'learning_rate': 0.28259703707559747, 'max_depth': 2, 'min_child_weight': 7, 'gamma': 0.7371298852154179, 'reg_alpha': 0.13240306841182287, 'reg_lambda': 0.1684610178641428}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,312] Trial 44 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 278, 'learning_rate': 0.7361302371919207, 'max_depth': 8, 'min_child_weight': 4, 'gamma': 0.5506565590341044, 'reg_alpha': 0.18158605901386826, 'reg_lambda': 0.10525495383445792}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,314] Trial 45 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 159, 'learning_rate': 0.3339932414284492}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,316] Trial 46 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 511, 'learning_rate': 0.2301234448780595}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,321] Trial 47 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 94, 'learning_rate': 0.8829096782882914, 'max_depth': 5, 'min_child_weight': 9, 'gamma': 0.9713082371649185, 'reg_alpha': 0.31570548121068637, 'reg_lambda': 0.20653688573902573}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,323] Trial 48 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 261, 'learning_rate': 0.45540066924004163}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,327] Trial 49 finished with value: 0.9212678936605317 and parameters: {'booster': 'dart', 'n_estimators': 671, 'learning_rate': 0.34462645725560154, 'max_depth': 13, 'min_child_weight': 7, 'gamma': 0.40881231797790296, 'reg_alpha': 0.12213267983724836, 'reg_lambda': 0.2650186514646592}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,329] Trial 50 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 54, 'learning_rate': 0.5630572962932632}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,334] Trial 51 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 980, 'learning_rate': 0.3904501385544145, 'max_depth': 13, 'min_child_weight': 2, 'gamma': 0.22411028300222605, 'reg_alpha': 0.218186154117793, 'reg_lambda': 0.7737460930330418}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,338] Trial 52 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 414, 'learning_rate': 0.29193594181285176, 'max_depth': 13, 'min_child_weight': 2, 'gamma': 0.277047370407076, 'reg_alpha': 0.16773363194005755, 'reg_lambda': 0.6157114872111393}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,343] Trial 53 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 739, 'learning_rate': 0.26825754164330806, 'max_depth': 9, 'min_child_weight': 2, 'gamma': 0.24409303424318668, 'reg_alpha': 0.21614503629204423, 'reg_lambda': 0.4024236477785074}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,347] Trial 54 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 554, 'learning_rate': 0.11481022617941755, 'max_depth': 14, 'min_child_weight': 5, 'gamma': 0.14419687300645845, 'reg_alpha': 0.13619661036908695, 'reg_lambda': 0.557496092086213}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,352] Trial 55 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 566, 'learning_rate': 0.4748279181432579, 'max_depth': 7, 'min_child_weight': 3, 'gamma': 0.7456097727460755, 'reg_alpha': 0.16393686949879388, 'reg_lambda': 0.9935447461636155}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,354] Trial 56 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 224, 'learning_rate': 0.661881694182988}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,358] Trial 57 finished with value: 0.9212678936605317 and parameters: {'booster': 'dart', 'n_estimators': 441, 'learning_rate': 0.21223602901152352, 'max_depth': 11, 'min_child_weight': 1, 'gamma': 0.5407333858758491, 'reg_alpha': 0.10031793373238167, 'reg_lambda': 0.11796017297665991}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,363] Trial 58 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 323, 'learning_rate': 0.4214085123634521, 'max_depth': 9, 'min_child_weight': 4, 'gamma': 0.39174782048816675, 'reg_alpha': 0.30237943740202156, 'reg_lambda': 0.15162434413460874}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,365] Trial 59 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 161, 'learning_rate': 0.7685519345594449}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,370] Trial 60 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 866, 'learning_rate': 0.255134918773991, 'max_depth': 11, 'min_child_weight': 2, 'gamma': 0.6988041456027417, 'reg_alpha': 0.21603429902876026, 'reg_lambda': 0.10003359669960153}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,375] Trial 61 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 9, 'learning_rate': 0.5973889473770786, 'max_depth': 7, 'min_child_weight': 9, 'gamma': 0.8636731416232254, 'reg_alpha': 0.9394972049916613, 'reg_lambda': 0.11551040330684277}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,380] Trial 62 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 14, 'learning_rate': 0.36550035924326935, 'max_depth': 6, 'min_child_weight': 8, 'gamma': 0.8471736446177259, 'reg_alpha': 0.7668916866604238, 'reg_lambda': 0.11621873949699596}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,385] Trial 63 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 7, 'learning_rate': 0.5778664200819776, 'max_depth': 1, 'min_child_weight': 10, 'gamma': 0.19567871548374186, 'reg_alpha': 0.37299786237375393, 'reg_lambda': 0.12852665904436503}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,387] Trial 64 finished with value: 0.9212678936605317 and parameters: {'booster': 'gblinear', 'n_estimators': 29, 'learning_rate': 0.7028318268157934}. Best is trial 0 with value: 0.9212678936605317.
[I 2025-11-01 14:58:02,391] Trial 65 finished with value: 0.9212678936605317 and parameters: {'booster': 'gbtree', 'n_estimators': 6, 'learning_rate': 0.5280381426099572, 'max_depth': 8, 'min_child_weight': 8, 'gamma': 0.49275322153392775, 'reg_alpha': 0.781586530662062, 'reg_lambda': 0.1757973842821243}. Best is trial 0 with value: 0.9212678936605317.

In [49]:
study.best_params

{'booster': 'gblinear',
 'n_estimators': 632,
 'learning_rate': 0.29019543782476226}

In [50]:
study_params = study.best_params
xgboost = XGBClassifier(**study_params)
xgboost.fit(X_train,y_train)
y_pred = xgboost.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.83640081799591

In [1]:
def object(trial):
    params = {
        'max_depth': trial.suggest_int('max_depth',low=1,high=15,step=1),
        'n_estimators': trial.suggest_int('n_estimators',low=5,high=1000,log=True),
        'min_sample_split': trial.suggest_int('min_sample_split',low=2,high=10,step=1)
    }
    model = RandomForestClassifier(**params)
    accuracy = accuracy_score(y_test,y_pred)
    return accuracy
study = optuna.create_study(direction='maximize')
study.optimize(object, n_trials=1000)

NameError: name 'optuna' is not defined