In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import r2_score,mean_absolute_error

In [14]:
df = sns.load_dataset('tips')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

# FEATURE ENCODING

In [15]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [16]:
X = df[[ 'tip', 'sex', 'smoker', 'day', 'time', 'size']]
y = df['total_bill']

In [17]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=10)

In [18]:
X_train

      tip     sex smoker   day    time  size
58   1.76    Male    Yes   Sat  Dinner     2
1    1.66    Male     No   Sun  Dinner     3
2    3.50    Male     No   Sun  Dinner     3
68   2.01    Male     No   Sat  Dinner     2
184  3.00    Male    Yes   Sun  Dinner     2
..    ...     ...    ...   ...     ...   ...
64   2.64    Male     No   Sat  Dinner     3
15   3.92    Male     No   Sun  Dinner     2
228  2.72    Male     No   Sat  Dinner     2
125  4.20  Female     No  Thur   Lunch     6
9    3.23    Male     No   Sun  Dinner     2

[183 rows x 6 columns]

In [19]:
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

In [20]:
X_train['sex'] = le1.fit_transform(X_train['sex'])
X_train['smoker'] = le2.fit_transform(X_train['smoker'])
X_train['time'] = le3.fit_transform(X_train['time'])

In [21]:
X_train

      tip  sex  smoker   day  time  size
58   1.76    1       1   Sat     0     2
1    1.66    1       0   Sun     0     3
2    3.50    1       0   Sun     0     3
68   2.01    1       0   Sat     0     2
184  3.00    1       1   Sun     0     2
..    ...  ...     ...   ...   ...   ...
64   2.64    1       0   Sat     0     3
15   3.92    1       0   Sun     0     2
228  2.72    1       0   Sat     0     2
125  4.20    0       0  Thur     1     6
9    3.23    1       0   Sun     0     2

[183 rows x 6 columns]

In [22]:
X_test['sex'] = le1.transform(X_test['sex'])
X_test['smoker'] = le2.transform(X_test['smoker'])
X_test['time'] = le3.transform(X_test['time'])

In [27]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(drop='first'), [3])],remainder='passthrough')

In [28]:
X_train = ct.fit_transform(X_train)

In [29]:
X_train

array([[1., 0., 0., ..., 1., 0., 2.],
       [0., 1., 0., ..., 0., 0., 3.],
       [0., 1., 0., ..., 0., 0., 3.],
       ...,
       [1., 0., 0., ..., 0., 0., 2.],
       [0., 0., 1., ..., 0., 1., 6.],
       [0., 1., 0., ..., 0., 0., 2.]])

In [30]:
X_test = ct.transform(X_test)

In [31]:
svr = SVR(kernel='rbf')
svr.fit(X_train,y_train)
y_pred = svr.predict(X_test)

In [33]:
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.46028114561159283
4.1486423210190235